
# Edit script for SI.tex -- expand individual energy distribution derivations
filepath = "C:/Users/Eugenio/Dropbox/000My_Drafts/050-Isotherm_guidelines/SI.tex"

with open(filepath, 'rb') as f:
    content = f.read()

lines = content.split(b'\n')
print("Line 1542:", repr(lines[1541][:60]))
print("Line 1764:", repr(lines[1763][:60]))
print("Line 1765:", repr(lines[1764][:60]))

def L(*args):
    parts = []
    for a in args:
        if isinstance(a, str):
            a = a.encode('utf-8')
        parts.append(a)
    return b''.join(parts)

# Tab for indentation inside environments
T = b'\t'

new_sec = [
L(b'\\subsection{Individual energy distributions and $\\sigma_E$ derivations}'),
L(b'\\label{sec:si_individual_distributions}'),
b'',
L(b'The condensation approximation (Section~\\ref{sec:si_energy_framework}) is applied'),
L(b'to each isotherm by substituting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$ and computing'),
L(b'$f(E) = -(1/Q_{\\max})\\,\\mathrm{d}q/\\mathrm{d}E$. The standard deviation $\\sigma_E$'),
L(b'is then obtained from the variance of the resulting distribution family.'),
b'',
b'% ------ Langmuir ------',
L(b'\\subsubsection{Langmuir}'),
b'',
L(b'\\paragraph{Exact result.}'),
L(b'The Langmuir isotherm is obtained \\emph{exactly} by setting'),
L(b'$f(E) = \\delta(E-E_c)$ in Eq.~\\eqref{eq:si_heterogeneous_integral}:'),
L(b'\\begin{equation}'),
L(T, b'Q_{\\max}\\int_0^{\\infty}\\frac{K(E)\\,C_e}{1+K(E)\\,C_e}'),
L(T, b'\\,\\delta(E-E_c)\\,\\mathrm{d}E'),
L(T, b'= Q_{\\max}\\,\\frac{K_L\\,C_e}{1+K_L\\,C_e},'),
L(T, b'\\qquad K_L = K_0\\mathrm{e}^{E_c/RT}.'),
L(b'\\end{equation}'),
L(b'No condensation approximation is needed: the Langmuir isotherm is \\emph{exact}'),
L(b'for a homogeneous surface ($\\sigma_E = 0$).'),
b'',
L(b'\\paragraph{Characteristic energy and width.}'),
L(b'\\begin{equation}'),
L(T, b'E_c = RT\\ln(K_L\\,C^{\\ast}), \\qquad \\sigma_E = 0.'),
L(b'\\end{equation}'),
b'',
b'% ------ Double Langmuir ------',
L(b'\\subsubsection{Double Langmuir}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'The double-Langmuir isotherm follows from a bimodal discrete distribution:'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{Q_1}{Q_{\\max}}\\,\\delta(E-E_1)'),
L(T, b'     + \\frac{Q_2}{Q_{\\max}}\\,\\delta(E-E_2),'),
L(T, b'\\qquad Q_{\\max} = Q_1+Q_2,'),
L(b'\\end{equation}'),
L(b'with $E_i = RT\\ln(K_i\\,C^{\\ast})$.'),
b'',
L(b'\\paragraph{Derivation of $\\sigma_E$.}'),
L(b'For a two-point distribution with weights $w_i = Q_i/Q_{\\max}$:'),
L(b'\\begin{align}'),
L(T, b'\\langle E \\rangle &= w_1 E_1 + w_2 E_2, \\\\'),
L(T, b'\\sigma_E^2 &= w_1(E_1-\\langle E\\rangle)^2 + w_2(E_2-\\langle E\\rangle)^2'),
L(T, b'           = w_1 w_2\\,(E_1-E_2)^2,'),
L(b'\\end{align}'),
L(b'therefore'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_E = \\frac{\\sqrt{Q_1 Q_2}}{Q_1+Q_2}\\,|\\Delta E_{12}|,'),
L(T, b'\\qquad \\Delta E_{12} = E_1 - E_2.'),
L(T, b'\\label{eq:si_sigmaE_DL}'),
L(b'\\end{equation}'),
L(b'For equal sites ($Q_1=Q_2$): $\\sigma_E = |\\Delta E_{12}|/2$.'),
b'',
b'% ------ Sips ------',
L(b'\\subsubsection{Sips (Langmuir--Freundlich)}'),
L(b'\\label{sec:si_sips_dist}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = Q_{\\max}\\,\\frac{K_S C_e^{m}}{1 + K_S C_e^{m}},'),
L(T, b'\\qquad 0 < m \\leq 1.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Condensation substitution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$ and defining'),
L(b'$E_c = (RT/m)\\ln[K_S(C^{\\ast})^{m}] = RT\\ln(K_S^{1/m}C^{\\ast})$:'),
L(b'\\begin{equation}'),
L(T, b'q(E) = \\frac{Q_{\\max}}{1+\\mathrm{e}^{m(E-E_c)/RT}}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Differentiation.}'),
L(b'\\begin{equation}'),
L(T, b'\\frac{\\mathrm{d}q}{\\mathrm{d}E}'),
L(T, b'= -Q_{\\max}\\,\\frac{(m/RT)\\,\\mathrm{e}^{m(E-E_c)/RT}}'),
L(T, b'           {\\bigl[1+\\mathrm{e}^{m(E-E_c)/RT}\\bigr]^{2}}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{Q_{\\max}\\,(m/RT)\\,\\mathrm{e}^{m(E-E_c)/RT}}'),
L(T, b'           {\\bigl[1+\\mathrm{e}^{m(E-E_c)/RT}\\bigr]^{2}}.'),
L(T, b'\\label{eq:si_fE_sips}'),
L(b'\\end{equation}'),
L(b'This is the \\textbf{logistic} probability density (times $Q_{\\max}$)'),
L(b'with location $E_c$ and scale $s = RT/m$.'),
b'',
L(b'\\paragraph{Width.}'),
L(b'The variance of the logistic distribution with scale $s$ is $\\pi^2 s^2/3$, so'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_E = \\frac{\\pi}{\\sqrt{3}}\\,\\frac{RT}{m}.'),
L(T, b'\\label{eq:si_sigmaE_sips}'),
L(b'\\end{equation}'),
L(b'For $m=1$ (Langmuir): $\\sigma_E = (\\pi/\\sqrt{3})\\,RT \\approx 1.81\\,RT$.'),
L(b'As $m \\to 0$: $\\sigma_E \\to \\infty$ (Freundlich limit).'),
b'',
b"% ------ Toth ------",
L(b"\\subsubsection{T\\'{o}th}"),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = \\frac{q_{\\max}\\, b\\, C_e}{\\bigl[1+(b C_e)^{t}\\bigr]^{1/t}},'),
L(T, b'\\qquad 0 < t \\leq 1.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Condensation substitution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$, $E_c = RT\\ln(bC^{\\ast})$,'),
L(b'$u = (E-E_c)/RT$:'),
L(b'\\begin{equation}'),
L(T, b'q(E) = q_{\\max}\\,\\frac{\\mathrm{e}^{-u}}{\\bigl[1+\\mathrm{e}^{-tu}\\bigr]^{1/t}}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Differentiation.}'),
L(b'Applying the product rule and collecting terms:'),
L(b'\\begin{equation}'),
L(T, b'\\frac{\\mathrm{d}q}{\\mathrm{d}E}'),
L(T, b'= -\\frac{q_{\\max}}{RT}\\,\\frac{\\mathrm{e}^{-u}}'),
L(T, b'                               {\\bigl[1+\\mathrm{e}^{-tu}\\bigr]^{(1+t)/t}},'),
L(T, b'\\qquad u = \\frac{E-E_c}{RT}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{q_{\\max}}{RT}\\,'),
L(T, b'\\frac{\\mathrm{e}^{-u}}'),
L(T, b'{[1 + \\mathrm{e}^{-tu}]^{(1+t)/t}},'),
L(T, b'\\qquad u = \\frac{E - E_c}{RT}.'),
L(T, b'\\label{eq:si_fE_toth}'),
L(b'\\end{equation}'),
L(b'This is the \\textbf{generalised logistic type IV}, asymmetric with a heavier tail'),
L(b'toward \\emph{low} adsorption energies for $t < 1$.'),
L(b'For $t = 1$ it reduces to the standard logistic (Langmuir limit).'),
b'',
L(b'\\paragraph{Width.}'),
L(b'No closed-form $\\sigma_E$ exists for general $t$; numerical integration is required.'),
L(b'$\\sigma_E > (\\pi/\\sqrt{3})\\,RT$ for all $t < 1$, diverging as $t \\to 0$.'),
b'',
b'% ------ Jovanovic ------',
L(b'\\subsubsection{Jovanovic}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = q_{\\max}\\bigl[1 - \\exp(-b C_e)\\bigr].'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Condensation substitution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$, $E_c = RT\\ln(bC^{\\ast})$,'),
L(b'$u = (E-E_c)/RT$:'),
L(b'\\begin{equation}'),
L(T, b'q(E) = q_{\\max}\\!\\left[1 - \\exp\\!\\left(-\\mathrm{e}^{-u}\\right)\\right].'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Differentiation.}'),
L(b'\\begin{equation}'),
L(T, b'\\frac{\\mathrm{d}q}{\\mathrm{d}E}'),
L(T, b'= -\\frac{q_{\\max}}{RT}\\,\\mathrm{e}^{-u}\\exp\\!\\left(-\\mathrm{e}^{-u}\\right).'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{q_{\\max}}{RT}\\,\\mathrm{e}^{-u}\\exp\\!\\left(-\\mathrm{e}^{-u}\\right),'),
L(T, b'\\qquad u = \\frac{E-E_c}{RT}.'),
L(T, b'\\label{eq:si_fE_jov}'),
L(b'\\end{equation}'),
L(b'This is the \\textbf{Gumbel (extreme-value type I)} distribution with location $E_c$'),
L(b'and scale $RT$. The mean is $\\langle E\\rangle = E_c + \\gamma\\,RT$'),
L(b'($\\gamma \\approx 0.5772$, Euler--Mascheroni constant).'),
L(b'The distribution is asymmetric with a longer tail toward \\emph{high} energies.'),
b'',
L(b'\\paragraph{Width.}'),
L(b'The variance of the Gumbel distribution with scale $\\beta$ is $\\pi^2\\beta^2/6$:'),
L(b'\\begin{equation}'),
L(T, b'E_c = RT\\ln(bC^{\\ast}),'),
L(T, b'\\qquad'),
L(T, b'\\sigma_E = \\frac{\\pi}{\\sqrt{6}}\\,RT \\approx 1.283\\,RT.'),
L(T, b'\\label{eq:si_sigmaE_jov}'),
L(b'\\end{equation}'),
L(b'The width is independent of the affinity parameter $b$ and is fixed solely by'),
L(b'the model functional form.'),
b'',
b'% ------ Temkin ------',
L(b'\\subsubsection{Temkin}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = \\frac{RT}{b_T}\\ln(a_T C_e).'),
L(b'\\end{equation}'),
L(b'(Valid over the intermediate concentration range where the log-linear'),
L(b'approximation holds; implicitly defines $[E_{\\min}, E_{\\max}]$.)'),
b'',
L(b'\\paragraph{Condensation substitution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$:'),
L(b'\\begin{equation}'),
L(T, b'q(E) = \\frac{1}{b_T}\\bigl[RT\\ln(a_T C^{\\ast}) - E\\bigr].'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'\\begin{equation}'),
L(T, b'f(E) = -\\frac{1}{Q_{\\max}}\\frac{\\mathrm{d}q}{\\mathrm{d}E}'),
L(T, b'= \\frac{Q_{\\max}}{b_T Q_{\\max}} = \\frac{1}{b_T} = \\text{const},'),
L(T, b'\\qquad E_{\\min} \\leq E \\leq E_{\\max}.'),
L(T, b'\\label{eq:si_fE_temkin}'),
L(b'\\end{equation}'),
L(b'This is a \\textbf{uniform (rectangular)} distribution over $[E_{\\min}, E_{\\max}]$,'),
L(b'where $E_{\\max} = RT\\ln(a_T C^{\\ast})$ and $E_{\\max} - E_{\\min} = b_T Q_{\\max}$.'),
b'',
L(b'\\paragraph{Width.}'),
L(b'For a uniform distribution on $[a,b]$, $\\sigma = (b-a)/(2\\sqrt{3})$:'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_E = \\frac{E_{\\max}-E_{\\min}}{2\\sqrt{3}}'),
L(T, b'= \\frac{b_T\\,Q_{\\max}}{2\\sqrt{3}}.'),
L(T, b'\\label{eq:si_sigmaE_temkin}'),
L(b'\\end{equation}'),
b'',
b'% ------ UNILAN ------',
L(b'\\subsubsection{UNILAN}'),
b'',
L(b'\\paragraph{Exact integration.}'),
L(b'UNILAN retains the full Langmuir kernel and integrates over a uniform distribution'),
L(b'$f(E) = Q_{\\max}/(2s)$ on $[E_c-s,\\,E_c+s]$ analytically:'),
L(b'\\begin{align}'),
L(T, b'q_e &= \\frac{Q_{\\max}}{2s}\\int_{E_c-s}^{E_c+s}'),
L(T, b'\\frac{K_0\\mathrm{e}^{E/RT}\\,C_e}{1+K_0\\mathrm{e}^{E/RT}\\,C_e}\\,\\mathrm{d}E'),
L(T, b'\\notag \\\\'),
L(T, b'&= \\frac{Q_{\\max}\\,RT}{2s}'),
L(T, b'\\ln\\!\\frac{1+b_{\\max}\\,C_e}{1+b_{\\min}\\,C_e},'),
L(T, b'\\qquad b_{\\max/\\min} = K_0\\,\\mathrm{e}^{(E_c\\pm s)/RT}.'),
L(b'\\end{align}'),
b'',
L(b'\\paragraph{Distribution and width.}'),
L(b'By construction:'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{Q_{\\max}}{2s} = \\text{const},'),
L(T, b'\\qquad s = \\frac{RT}{2}\\ln\\!\\frac{b_{\\max}}{b_{\\min}}.'),
L(T, b'\\label{eq:si_fE_unilan}'),
L(b'\\end{equation}'),
L(b'The standard deviation of the uniform distribution on $[E_c-s,\\,E_c+s]$ is $s/\\sqrt{3}$:'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_E = \\frac{s}{\\sqrt{3}}'),
L(T, b'= \\frac{RT}{2\\sqrt{3}}\\ln\\!\\frac{b_{\\max}}{b_{\\min}}.'),
L(T, b'\\label{eq:si_sigmaE_unilan}'),
L(b'\\end{equation}'),
b'',
b'% ------ Freundlich ------',
L(b'\\subsubsection{Freundlich}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = K_F C_e^{1/n}, \\qquad 0 < 1/n < 1.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Condensation substitution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$:'),
L(b'\\begin{equation}'),
L(T, b'q(E) = K_F(C^{\\ast})^{1/n}\\,\\mathrm{e}^{-E/(nRT)}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{K_F(C^{\\ast})^{1/n}}{nRT}\\,\\mathrm{e}^{-E/(nRT)}.'),
L(T, b'\\label{eq:si_fE_freundlich}'),
L(b'\\end{equation}'),
L(b'This one-sided exponential does \\emph{not} normalise to a finite area on'),
L(b'$[0,\\infty)$, reflecting the absence of a finite $Q_{\\max}$.'),
b'',
L(b'\\paragraph{Width.}'),
L(b'$\\sigma_E = \\infty$. The Freundlich model cannot be interpreted as arising from'),
L(b'a physically normalised site-energy distribution; it is a purely empirical'),
L(b'fitting equation valid only over a limited concentration window.'),
b'',
b'% ------ Redlich-Peterson ------',
L(b'\\subsubsection{Redlich--Peterson}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = \\frac{K_{RP}\\,C_e}{1 + a_{RP}\\,C_e^{\\beta}},'),
L(T, b'\\qquad 0 < \\beta \\leq 1.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Condensation substitution and distribution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$ and differentiating:'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{K_{RP}\\,C^{\\ast}\\mathrm{e}^{-E/RT}}{Q_{\\max}\\,RT}'),
L(T, b'\\cdot\\frac{1+(1-\\beta)\\,a_{RP}(C^{\\ast})^{\\beta}\\mathrm{e}^{-\\beta E/RT}}'),
L(T, b'          {\\bigl[1+a_{RP}(C^{\\ast})^{\\beta}\\mathrm{e}^{-\\beta E/RT}\\bigr]^{2}}.'),
L(T, b'\\label{eq:si_fE_RP}'),
L(b'\\end{equation}'),
L(b'For $\\beta = 1$: reduces to the logistic density (Langmuir). For $\\beta < 1$:'),
L(b'non-standard asymmetric form with no closed-form $\\sigma_E$.'),
b'',
b'% ------ Koble-Corrigan ------',
L(b'\\subsubsection{Koble--Corrigan}'),
b'',
L(b'\\paragraph{Equivalence to Sips.}'),
L(b'The Koble--Corrigan isotherm'),
L(b'$q_e = A_{KC}\\,C_e^{m}\\,/\\,(1 + B_{KC}\\,C_e^{m})$'),
L(b'is algebraically identical to Sips with $Q_{\\max} = A_{KC}/B_{KC}$ and'),
L(b'$K_S = B_{KC}$, same exponent $m$.'),
L(b'The energy distribution and $\\sigma_E$ are therefore those of'),
L(b'Section~\\ref{sec:si_sips_dist}:'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_E = \\frac{\\pi}{\\sqrt{3}}\\,\\frac{RT}{m}.'),
L(b'\\end{equation}'),
b'',
b'% ------ Radke-Prausnitz ------',
L(b'\\subsubsection{Radke--Prausnitz}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = \\frac{a_{RP}\\,r_{RP}\\,C_e}{a_{RP} + r_{RP}\\,C_e^{p}},'),
L(T, b'\\qquad 0 < p \\leq 1.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'Applying the condensation substitution yields a non-standard distribution'),
L(b'without a simple closed form. No analytical $\\sigma_E$ exists; numerical'),
L(b'integration is required. For $p \\to 0$ the distribution approaches a'),
L(b'logarithmic form with diverging width; for $p = 1$ it reduces to the'),
L(b'Langmuir (logistic) distribution.'),
b'',
b'% ------ D-R / D-A ------',
L(b'\\subsubsection{Dubinin--Radushkevich / Dubinin--Astakhov}'),
b'',
L(b'\\paragraph{Polanyi potential.}'),
L(b'D-R and D-A operate in the Polanyi adsorption potential'),
L(b'$\\varepsilon = RT\\ln(1 + 1/C_e)$ rather than directly in $E$.'),
L(b'The isotherm is'),
L(b'\\begin{equation}'),
L(T, b'q_e = Q_{\\max}\\exp\\!\\left[-\\!\\left(\\frac{\\varepsilon}{E_a}\\right)^{\\!n_{DA}}\\right].'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Derivation of $f(\\varepsilon)$.}'),
L(b'Differentiating with respect to $\\varepsilon$:'),
L(b'\\begin{equation}'),
L(T, b'f(\\varepsilon) = -\\frac{1}{Q_{\\max}}\\frac{\\mathrm{d}q}{\\mathrm{d}\\varepsilon}'),
L(T, b'= \\frac{n_{DA}}{E_a}\\left(\\frac{\\varepsilon}{E_a}\\right)^{n_{DA}-1}'),
L(T, b'\\exp\\!\\left[-\\!\\left(\\frac{\\varepsilon}{E_a}\\right)^{n_{DA}}\\right].'),
L(T, b'\\label{eq:si_fE_DA}'),
L(b'\\end{equation}'),
L(b'This is the \\textbf{Weibull} probability density with scale $E_a$'),
L(b'and shape $n_{DA}$.'),
b'',
L(b'\\paragraph{Mean adsorption potential.}'),
L(b'\\begin{equation}'),
L(T, b'\\langle\\varepsilon\\rangle'),
L(T, b'= \\frac{E_a}{n_{DA}}\\,\\Gamma\\!\\left(\\frac{1}{n_{DA}}\\right).'),
L(b'\\end{equation}'),
L(b'D-R ($n_{DA}=2$): $\\langle\\varepsilon\\rangle = E_a\\sqrt{\\pi}/2$.'),
b'',
L(b'\\paragraph{Width.}'),
L(b'The variance of the Weibull distribution with scale $E_a$ and shape $n_{DA}$ is'),
L(b'$E_a^2[\\Gamma(1+2/n_{DA})-\\Gamma(1+1/n_{DA})^2]$, therefore'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_\\varepsilon'),
L(T, b'= E_a\\sqrt{\\Gamma\\!\\left(1+\\frac{2}{n_{DA}}\\right)'),
L(T, b'           - \\left[\\Gamma\\!\\left(1+\\frac{1}{n_{DA}}\\right)\\right]^{2}}.'),
L(T, b'\\label{eq:si_sigmaE_DA}'),
L(b'\\end{equation}'),
L(b'D-R ($n_{DA}=2$): $\\Gamma(2)=1$, $\\Gamma(3/2)=\\sqrt{\\pi}/2$, so'),
L(b'\\begin{equation}'),
L(T, b'\\sigma_\\varepsilon = E_a\\sqrt{1-\\pi/4} \\approx 0.4633\\,E_a.'),
L(b'\\end{equation}'),
L(b'The distribution is right-skewed (longer tail toward high adsorption potentials).'),
b'',
b'% ------ Hill ------',
L(b'\\subsubsection{Hill}'),
b'',
L(b'\\paragraph{Starting isotherm.}'),
L(b'\\begin{equation}'),
L(T, b'q_e = \\frac{Q_{\\max}\\,C_e^{n_H}}{K_D + C_e^{n_H}}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Condensation substitution.}'),
L(b'Setting $C_e = C^{\\ast}\\mathrm{e}^{-E/RT}$ and defining'),
L(b'$E_c = RT\\ln(K_D^{-1/n_H}\\,C^{\\ast})$:'),
L(b'\\begin{equation}'),
L(T, b'q(E) = \\frac{Q_{\\max}}{1+\\mathrm{e}^{n_H(E-E_c)/RT}}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Differentiation.}'),
L(b'\\begin{equation}'),
L(T, b'\\frac{\\mathrm{d}q}{\\mathrm{d}E}'),
L(T, b'= -Q_{\\max}\\,\\frac{(n_H/RT)\\,\\mathrm{e}^{n_H(E-E_c)/RT}}'),
L(T, b'           {\\bigl[1+\\mathrm{e}^{n_H(E-E_c)/RT}\\bigr]^{2}}.'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Distribution.}'),
L(b'\\begin{equation}'),
L(T, b'f(E) = \\frac{Q_{\\max}\\,(n_H/RT)\\,\\mathrm{e}^{n_H(E-E_c)/RT}}'),
L(T, b'           {\\bigl[1+\\mathrm{e}^{n_H(E-E_c)/RT}\\bigr]^{2}}.'),
L(T, b'\\label{eq:si_fE_Hill}'),
L(b'\\end{equation}'),
L(b'Logistic density (times $Q_{\\max}$) with location $E_c$ and scale $s = RT/n_H$;'),
L(b'identical in form to Sips (Section~\\ref{sec:si_sips_dist}) with $m \\to n_H$.'),
b'',
L(b'\\paragraph{Width.}'),
L(b'\\begin{equation}'),
L(T, b'E_c = RT\\ln(K_D^{-1/n_H}\\,C^{\\ast}),'),
L(T, b'\\qquad'),
L(T, b'\\sigma_E = \\frac{\\pi}{\\sqrt{3}}\\,\\frac{RT}{n_H}.'),
L(T, b'\\label{eq:si_sigmaE_Hill}'),
L(b'\\end{equation}'),
b'',
L(b'\\paragraph{Physical interpretation.}'),
L(b'\\begin{itemize}'),
L(T, b'\\item $n_H < 1$ (anti-cooperative): $\\sigma_E > (\\pi/\\sqrt{3})\\,RT$ --- broader than Langmuir.'),
L(T, b'\\item $n_H = 1$ (non-cooperative): $\\sigma_E = (\\pi/\\sqrt{3})\\,RT \\approx 1.81\\,RT$.'),
L(T, b'\\item $n_H > 1$ (cooperative binding): $\\sigma_E < (\\pi/\\sqrt{3})\\,RT$ ---'),
L(T, b'      narrower distribution; the adsorption transition is sharper.'),
L(b'\\end{itemize}'),
b'',
]

result = lines[:1541] + new_sec + lines[1764:]
with open(filepath, 'wb') as f:
    f.write(b'\n'.join(result))

print(f"SI.tex written. Replacement has {len(new_sec)} lines. Total: {len(result)}")
