#!/usr/bin/env python3
"""Create a lightweight inventory of multimodal data files.

Usage:
  python scripts/scan_data.py data > memory/data_inventory.md

This script is intentionally token-efficient. It previews only small parts of text/table files
and reports metadata for images/binary files. It does not interpret the science.
"""
import argparse
from pathlib import Path
import csv
import json
import zipfile

TEXT_EXTS = {'.txt', '.csv', '.tsv', '.dat', '.md', '.json', '.log', '.asc'}
TABLE_EXTS = {'.csv', '.tsv'}
IMAGE_EXTS = {'.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp', '.webp'}
SPREADSHEET_EXTS = {'.xlsx', '.xlsm'}
NOTEBOOK_EXTS = {'.ipynb'}
PDF_EXTS = {'.pdf'}


def preview_text(path: Path, n=8):
    try:
        lines = path.read_text(encoding='utf-8', errors='replace').splitlines()
        return lines[:n]
    except Exception as e:
        return [f"[PREVIEW FAILED: {e}]"]


def table_info(path: Path):
    delim = '\t' if path.suffix.lower() == '.tsv' else ','
    try:
        with path.open('r', encoding='utf-8', errors='replace', newline='') as f:
            reader = csv.reader(f, delimiter=delim)
            rows = []
            for i, row in enumerate(reader):
                rows.append(row)
                if i >= 5:
                    break
        cols = rows[0] if rows else []
        return cols, rows[1:4]
    except Exception as e:
        return [f"[TABLE READ FAILED: {e}]"], []


def xlsx_info(path: Path):
    try:
        import openpyxl
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        out = []
        for ws in wb.worksheets[:10]:
            out.append(f"- Sheet: {ws.title}; rows: {ws.max_row}; columns: {ws.max_column}")
            sample = []
            for row in ws.iter_rows(min_row=1, max_row=min(ws.max_row, 4), values_only=True):
                sample.append([str(x) if x is not None else "" for x in row[:10]])
            if sample:
                out.append(f"  - Sample: {sample}")
        return out
    except Exception as e:
        return [f"- XLSX preview failed: {e}"]


def image_info(path: Path):
    try:
        from PIL import Image
        with Image.open(path) as im:
            return [f"- Image size: {im.size[0]} x {im.size[1]}", f"- Image mode: {im.mode}"]
    except Exception as e:
        return [f"- Image metadata failed: {e}"]


def notebook_info(path: Path):
    try:
        obj = json.loads(path.read_text(encoding='utf-8', errors='replace'))
        cells = obj.get('cells', [])
        code = sum(1 for c in cells if c.get('cell_type') == 'code')
        md = sum(1 for c in cells if c.get('cell_type') == 'markdown')
        headings = []
        for c in cells:
            if c.get('cell_type') == 'markdown':
                src = ''.join(c.get('source', []))
                for line in src.splitlines():
                    if line.startswith('#'):
                        headings.append(line[:120])
                        if len(headings) >= 8:
                            break
            if len(headings) >= 8:
                break
        return [f"- Notebook cells: {len(cells)}; code: {code}; markdown: {md}", f"- Headings: {headings}"]
    except Exception as e:
        return [f"- Notebook preview failed: {e}"]


def pdf_info(path: Path):
    out = []
    try:
        from pypdf import PdfReader
        reader = PdfReader(str(path))
        out.append(f"- PDF pages: {len(reader.pages)}")
        title = reader.metadata.title if reader.metadata else None
        if title:
            out.append(f"- PDF title: {title}")
    except Exception as e:
        out.append(f"- PDF page/title metadata unavailable: {e}")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('data_dir')
    args = ap.parse_args()
    base = Path(args.data_dir)
    print('# Multimodal Data Inventory')
    print('\nGenerated by scripts/scan_data.py. This is an inventory, not an interpretation. Agents must ask before inferring file meaning.\n')
    if not base.exists():
        print(f"[DATA DIR NOT FOUND] {base}")
        return
    files = [p for p in sorted(base.rglob('*')) if p.is_file() and p.name != '.gitkeep']
    if not files:
        print('[NO DATA FILES FOUND]')
        return
    for path in files:
        rel = path.relative_to(base)
        suffix = path.suffix.lower()
        print(f"## {rel}")
        print(f"- Size: {path.stat().st_size} bytes")
        print(f"- Extension: {suffix or '[none]'}")
        if suffix in TABLE_EXTS:
            cols, sample = table_info(path)
            print(f"- Columns: {cols}")
            print("- Sample rows:")
            for row in sample:
                print(f"  - {row}")
        elif suffix in SPREADSHEET_EXTS:
            for line in xlsx_info(path): print(line)
        elif suffix in IMAGE_EXTS:
            for line in image_info(path): print(line)
        elif suffix in NOTEBOOK_EXTS:
            for line in notebook_info(path): print(line)
        elif suffix in PDF_EXTS:
            for line in pdf_info(path): print(line)
        elif suffix in TEXT_EXTS:
            print("- Preview:")
            for line in preview_text(path):
                print(f"  > {line[:300]}")
        else:
            print("- Preview: binary or unsupported file type")
        print()

if __name__ == '__main__':
    main()
